version: 2
updates:
- package-ecosystem: npm
  directory: "/neural-network-app"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.1
    - 13.0.10
    - 13.0.14
    - 13.0.16
    - 13.0.3
    - 13.0.7
    - 13.0.8
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
