version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/neural-network-app"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"